### ISSUE TITLE
.NET MVC fork

### ISSUE THREAD

**Issue by WebstudioThomHubers** [goldenbull/ManagedXZ#5]
Hi,

It's not a PR because I understand you won't merge this, but take a look at my fork. The difference I made is that the dll's are retrieved from the /bin folder. Your version looked in a temporary folder (where ManagedXZ.dll was stored, but lzma files weren't.)

Thanks for all your effort!

**Comment by goldenbull** [comment]
Thanks for your comment. Currently, I didn't pay much attention on the path searching algorithm and just simply put the `lzma_amd64.dll` and `lzma_x86.dll` into the same folder as `ManagedXZ.dll`.
A question: what do you mean for "temporary folder"? Do you mean the output folder of the VS solution?

Seems grpc has demonstrated a better solution: https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/Internal/NativeExtension.cs#L119

**Comment by zgabi** [comment]
@WebstudioThomHubers In your fork you are not loading the files from the bin folder as you wrote in this issue.
You are loading it from the BaseDirectory:
https://github.com/WebstudioThomHubers/ManagedXZ/commit/28abf9ac10e37ecc4250a203afd9f8f1b30f423b

Since `Path.GetDirectoryName(thisdir)` removes the bin folder.
